### ISSUE TITLE
apt-get update fails in dependent image

### ISSUE THREAD

**Issue by DanLipsitt** [armhf-docker-library/debian#1]
Using the following Dockerfile,

```
FROM mazzolino/armhf-debian:wheezy

RUN which apt-get || exit 1
RUN apt-get update
```

I get this error:

```
$ docker build --force-rm .
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM mazzolino/armhf-debian:wheezy
 ---> 16250baa8bd8
Step 1 : RUN which apt-get || exit 1
 ---> Running in 4445a3150a75
Removing intermediate container 4445a3150a75
INFO[0000] no such file or directory      
```

I don't know how to tell what file or directory it is referring to. Note that the first `RUN` command in my Dockerfile confirms that it isn't apt-get itself that's missing.

This command works:

```
docker run --rm mazzolino/armhf-debian apt-get update
```

Depending on `mazzolino/armhf-ubuntu` gives the syscall error below, but the apt update works and the build completes.

```
Step 2 : RUN apt-get update
 ---> Running in 497b91637b4d
qemu: Unsupported syscall: 374
```

**Comment by djmaze** [comment]
You are running this on a non-ARM system (i.e. x86_64)? Please be aware that this image does not contain a qemu binary yet, so it can only be used on ARM systems as of now. This is the reason your first RUN command already fails.

The build script currently only works on ARM machines, too. I have yet to find a clean way to build on x86_64 and add the qemu exe.

**Comment by djmaze** [comment]
Sorry, I just realized I had qemu in the image description on the Docker hub. I now added qemu-arm-static manually and pushed a new image. So please do a `docker pull mazzolino/armhf-debian:wheezy` and it should work on x86_64 again.

**Comment by djmaze** [comment]
I modified the build script so it adds a static qemu binary for x86_64. The image still can only be built on an ARM machine, but the change makes sure that every new version will run on x86_64 from now on.
